project_name: 'Project name'
header_logo_url: 'assets/build/jetbrains-simple.svg'
render_toc_on_docs_layout: true
search: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"
